/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as TradeFinanceRouteImport } from './routes/trade-finance'
import { Route as TopupRouteImport } from './routes/topup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PiRouteImport } from './routes/pi'
import { Route as MoreRouteImport } from './routes/more'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LendingRouteImport } from './routes/lending'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as FxRouteImport } from './routes/fx'
import { Route as DepositsRouteImport } from './routes/deposits'
import { Route as CashRouteImport } from './routes/cash'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AssetsRouteImport } from './routes/assets'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PinetMetaRouteImport } from './routes/pinet.meta'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeFinanceRoute = TradeFinanceRouteImport.update({
  id: '/trade-finance',
  path: '/trade-finance',
  getParentRoute: () => rootRouteImport,
} as any)
const TopupRoute = TopupRouteImport.update({
  id: '/topup',
  path: '/topup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PiRoute = PiRouteImport.update({
  id: '/pi',
  path: '/pi',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LendingRoute = LendingRouteImport.update({
  id: '/lending',
  path: '/lending',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const FxRoute = FxRouteImport.update({
  id: '/fx',
  path: '/fx',
  getParentRoute: () => rootRouteImport,
} as any)
const DepositsRoute = DepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => rootRouteImport,
} as any)
const CashRoute = CashRouteImport.update({
  id: '/cash',
  path: '/cash',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AssetsRoute = AssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PinetMetaRoute = PinetMetaRouteImport.update({
  id: '/pinet/meta',
  path: '/pinet/meta',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/cards': typeof CardsRoute
  '/cash': typeof CashRoute
  '/deposits': typeof DepositsRoute
  '/fx': typeof FxRoute
  '/guide': typeof GuideRoute
  '/international': typeof InternationalRoute
  '/lending': typeof LendingRoute
  '/mcp': typeof McpRoute
  '/more': typeof MoreRoute
  '/pi': typeof PiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topup': typeof TopupRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/transfer': typeof TransferRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/pinet/meta': typeof PinetMetaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/cards': typeof CardsRoute
  '/cash': typeof CashRoute
  '/deposits': typeof DepositsRoute
  '/fx': typeof FxRoute
  '/guide': typeof GuideRoute
  '/international': typeof InternationalRoute
  '/lending': typeof LendingRoute
  '/mcp': typeof McpRoute
  '/more': typeof MoreRoute
  '/pi': typeof PiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topup': typeof TopupRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/transfer': typeof TransferRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/pinet/meta': typeof PinetMetaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assets': typeof AssetsRoute
  '/assistant': typeof AssistantRoute
  '/bills': typeof BillsRoute
  '/cards': typeof CardsRoute
  '/cash': typeof CashRoute
  '/deposits': typeof DepositsRoute
  '/fx': typeof FxRoute
  '/guide': typeof GuideRoute
  '/international': typeof InternationalRoute
  '/lending': typeof LendingRoute
  '/mcp': typeof McpRoute
  '/more': typeof MoreRoute
  '/pi': typeof PiRoute
  '/services': typeof ServicesRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/topup': typeof TopupRoute
  '/trade-finance': typeof TradeFinanceRoute
  '/transfer': typeof TransferRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/pinet/meta': typeof PinetMetaRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assets'
    | '/assistant'
    | '/bills'
    | '/cards'
    | '/cash'
    | '/deposits'
    | '/fx'
    | '/guide'
    | '/international'
    | '/lending'
    | '/mcp'
    | '/more'
    | '/pi'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/topup'
    | '/trade-finance'
    | '/transfer'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/pinet/meta'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assets'
    | '/assistant'
    | '/bills'
    | '/cards'
    | '/cash'
    | '/deposits'
    | '/fx'
    | '/guide'
    | '/international'
    | '/lending'
    | '/mcp'
    | '/more'
    | '/pi'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/topup'
    | '/trade-finance'
    | '/transfer'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/pinet/meta'
    | '/.mcp/invoke-tool/$tool'
  id:
    | '__root__'
    | '/'
    | '/assets'
    | '/assistant'
    | '/bills'
    | '/cards'
    | '/cash'
    | '/deposits'
    | '/fx'
    | '/guide'
    | '/international'
    | '/lending'
    | '/mcp'
    | '/more'
    | '/pi'
    | '/services'
    | '/settings'
    | '/sitemap.xml'
    | '/topup'
    | '/trade-finance'
    | '/transfer'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/pinet/meta'
    | '/.mcp/invoke-tool/$tool'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssetsRoute: typeof AssetsRoute
  AssistantRoute: typeof AssistantRoute
  BillsRoute: typeof BillsRoute
  CardsRoute: typeof CardsRoute
  CashRoute: typeof CashRoute
  DepositsRoute: typeof DepositsRoute
  FxRoute: typeof FxRoute
  GuideRoute: typeof GuideRoute
  InternationalRoute: typeof InternationalRoute
  LendingRoute: typeof LendingRoute
  McpRoute: typeof McpRoute
  MoreRoute: typeof MoreRoute
  PiRoute: typeof PiRoute
  ServicesRoute: typeof ServicesRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TopupRoute: typeof TopupRoute
  TradeFinanceRoute: typeof TradeFinanceRoute
  TransferRoute: typeof TransferRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  PinetMetaRoute: typeof PinetMetaRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-finance': {
      id: '/trade-finance'
      path: '/trade-finance'
      fullPath: '/trade-finance'
      preLoaderRoute: typeof TradeFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/topup': {
      id: '/topup'
      path: '/topup'
      fullPath: '/topup'
      preLoaderRoute: typeof TopupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pi': {
      id: '/pi'
      path: '/pi'
      fullPath: '/pi'
      preLoaderRoute: typeof PiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lending': {
      id: '/lending'
      path: '/lending'
      fullPath: '/lending'
      preLoaderRoute: typeof LendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fx': {
      id: '/fx'
      path: '/fx'
      fullPath: '/fx'
      preLoaderRoute: typeof FxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deposits': {
      id: '/deposits'
      path: '/deposits'
      fullPath: '/deposits'
      preLoaderRoute: typeof DepositsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cash': {
      id: '/cash'
      path: '/cash'
      fullPath: '/cash'
      preLoaderRoute: typeof CashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assets': {
      id: '/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pinet/meta': {
      id: '/pinet/meta'
      path: '/pinet/meta'
      fullPath: '/pinet/meta'
      preLoaderRoute: typeof PinetMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssetsRoute: AssetsRoute,
  AssistantRoute: AssistantRoute,
  BillsRoute: BillsRoute,
  CardsRoute: CardsRoute,
  CashRoute: CashRoute,
  DepositsRoute: DepositsRoute,
  FxRoute: FxRoute,
  GuideRoute: GuideRoute,
  InternationalRoute: InternationalRoute,
  LendingRoute: LendingRoute,
  McpRoute: McpRoute,
  MoreRoute: MoreRoute,
  PiRoute: PiRoute,
  ServicesRoute: ServicesRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TopupRoute: TopupRoute,
  TradeFinanceRoute: TradeFinanceRoute,
  TransferRoute: TransferRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  PinetMetaRoute: PinetMetaRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
